"""Small operational CLI.

    python -m app.cli init-db         # create tables
    python -m app.cli fetch           # fetch all feeds now
    python -m app.cli extract-facts   # mine anchor facts from stored articles
    python -m app.cli show-facts 3    # inspect one article's anchor facts
    python -m app.cli moods           # list available moods
    python -m app.cli rewrite 3 ironic  # rewrite one article (calls the LLM)
    python -m app.cli recheck 3 ironic  # re-run the fact check on a cached rewrite
    python -m app.cli stats           # what is currently stored

Inside Docker:  docker compose exec backend python -m app.cli fetch
"""

import argparse
import logging
import sys

from app.core.schema import init_db
from app.models import FactSet
from app.repositories import news_repository, rewrite_repository
from app.services.fact_extractor import backfill_facts, extract_facts
from app.services.llm_client import LLMError
from app.services.moods import MOODS, mood_keys
from app.services.news_fetcher import fetch_all
from app.services.rewriter import get_or_create_rewrite, recheck_rewrite


def _cmd_init_db() -> int:
    init_db()
    print("Schema created.")
    return 0


def _cmd_fetch() -> int:
    init_db()
    report = fetch_all()
    print(f"Inserted:    {report.inserted}")
    print(f"Duplicates:  {report.skipped_duplicates}")
    print(f"Feeds OK:    {', '.join(report.feeds_ok) or 'none'}")
    if report.feeds_failed:
        for name, error in report.feeds_failed.items():
            print(f"Feed FAILED: {name} -> {error}")
    print(f"Total in DB: {report.total_in_db}")
    # Every stored article needs its ground truth before it can be rewritten.
    print(f"Facts extracted for {backfill_facts()} new article(s)")
    # A run that stored nothing at all is a failure worth a non-zero exit code.
    return 0 if report.total_in_db else 1


def _cmd_extract_facts() -> int:
    init_db()
    print(f"Extracted anchor facts for {backfill_facts()} article(s).")
    return 0


def _cmd_show_facts(news_id: int) -> int:
    """Print one article's anchor facts - the ground truth for its rewrites."""
    init_db()
    article = news_repository.get_article(news_id)
    if article is None:
        print(f"No article with id {news_id}")
        return 1

    facts = (
        FactSet.model_validate_json(article.facts_json)
        if article.facts_json
        else extract_facts(article.original_text, article.title)
    )
    print(f"{article.title}\n{article.source_url}\n")
    for fact_type in ("number", "date", "quote", "name", "place"):
        of_type = facts.by_type(fact_type)
        if not of_type:
            continue
        marker = "!" if of_type[0].verbatim_required else " "
        print(f"{fact_type.upper()} ({len(of_type)}){marker}")
        for fact in of_type:
            seen = f" x{fact.occurrences}" if fact.occurrences > 1 else ""
            print(f"    {fact.text[:90]}{seen}")
        print()
    print(f"{len(facts.verbatim_facts)} fact(s) must appear verbatim in a rewrite.")
    return 0


def _cmd_moods() -> int:
    for mood in MOODS:
        print(f"{mood.key:<10} {mood.label:<10} {mood.description}")
    return 0


def _cmd_rewrite(news_id: int, mood: str, force: bool) -> int:
    """Rewrite one article in one mood. Hits the LLM unless already cached."""
    init_db()
    article = news_repository.get_article(news_id)
    if article is None:
        print(f"No article with id {news_id}")
        return 1

    try:
        rewrite, from_cache = get_or_create_rewrite(news_id, mood, force=force)
    except LookupError as exc:
        print(f"{exc}\nAvailable moods: {', '.join(mood_keys())}")
        return 1
    except LLMError as exc:
        print(f"Rewrite failed: {exc}")
        return 1

    print(f"{article.title}\n{article.source_url}")
    print(f"\nMood: {rewrite.mood}   "
          f"{'(from cache)' if from_cache else f'(generated by {rewrite.model})'}   "
          f"fact check: {rewrite.fact_check_status}")
    print("\n--- ORIGINAL " + "-" * 54)
    print(article.original_text[:1500])
    print("\n--- REWRITTEN " + "-" * 53)
    print(rewrite.rewritten_text[:1500])
    if rewrite.facts_preserved:
        print(f"\nModel claims it preserved {len(rewrite.facts_preserved)} fact(s).")
    _print_fact_check(rewrite)
    return 0


def _print_fact_check(rewrite) -> None:
    """Show both fact-check layers - including, and especially, a failure."""
    report = rewrite.fact_check_report
    print("\n--- FACT CHECK " + "-" * 52)
    print(f"status: {rewrite.fact_check_status.upper()}   attempts: {rewrite.attempts}")
    if report is None:
        print("(no detail stored)")
        return

    print(
        f"layer 1 (regex): {report.verbatim_verified}/{report.verbatim_total} "
        f"numbers, dates and quotes found verbatim"
    )
    for missing in report.missing_verbatim:
        print(f"    MISSING: {missing[:100]}")
    print(f"layer 2 (LLM auditor): {report.llm.status}")
    for item in report.llm.contradictions:
        print(f"    CONTRADICTION: {item[:120]}")
    for item in report.llm.missing_facts:
        print(f"    missing: {item[:120]}")
    print(f"summary: {report.summary}")


def _cmd_recheck(news_id: int, mood: str) -> int:
    """Re-verify a cached rewrite without paying for another rewriting call."""
    init_db()
    try:
        rewrite = recheck_rewrite(news_id, mood)
    except LookupError as exc:
        print(exc)
        return 1
    _print_fact_check(rewrite)
    return 0 if rewrite.fact_check_status != "failed" else 2


def _mood_summary(news_id: int) -> str:
    """Cached moods for one article, each with its fact-check verdict."""
    rewrites = rewrite_repository.list_rewrites(news_id)
    return ",".join(f"{r.mood}:{r.fact_check_status}" for r in rewrites) or "-"


def _cmd_stats() -> int:
    init_db()
    articles = news_repository.list_articles(limit=100)
    print(f"{len(articles)} article(s) stored, "
          f"{rewrite_repository.count_rewrites()} rewrite(s) cached\n")
    for article in articles:
        if article.facts_json:
            facts = FactSet.model_validate_json(article.facts_json)
            fact_summary = f"{len(facts.facts):>3} facts ({len(facts.verbatim_facts)} verbatim)"
        else:
            fact_summary = "  no facts yet"
        print(
            f"[{article.id:>3}] {article.source_name:<14} "
            f"{article.published_at or article.fetched_at}  "
            f"{len(article.original_text):>5} chars  {fact_summary}  "
            f"[{_mood_summary(article.id)}]  "
            f"{article.title[:40]}"
        )
    return 0


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")

    parser = argparse.ArgumentParser(prog="app.cli", description="MoodNews tools")
    parser.add_argument(
        "command",
        choices=[
            "init-db", "fetch", "extract-facts", "show-facts",
            "moods", "rewrite", "recheck", "stats",
        ],
    )
    parser.add_argument(
        "news_id",
        nargs="?",
        type=int,
        help="article id, for show-facts/rewrite/recheck",
    )
    parser.add_argument("mood", nargs="?", help="mood key, for rewrite/recheck")
    parser.add_argument(
        "--force",
        action="store_true",
        help="regenerate even when a cached rewrite exists",
    )
    args = parser.parse_args(argv)

    if args.command == "show-facts":
        if args.news_id is None:
            parser.error("show-facts needs an article id, e.g. show-facts 3")
        return _cmd_show_facts(args.news_id)

    if args.command == "recheck":
        if args.news_id is None or not args.mood:
            parser.error("recheck needs an article id and a mood, "
                         "e.g. recheck 3 ironic")
        return _cmd_recheck(args.news_id, args.mood)

    if args.command == "rewrite":
        if args.news_id is None or not args.mood:
            parser.error("rewrite needs an article id and a mood, "
                         "e.g. rewrite 3 ironic")
        return _cmd_rewrite(args.news_id, args.mood, args.force)

    return {
        "init-db": _cmd_init_db,
        "fetch": _cmd_fetch,
        "extract-facts": _cmd_extract_facts,
        "moods": _cmd_moods,
        "stats": _cmd_stats,
    }[args.command]()


if __name__ == "__main__":
    sys.exit(main())
